# Generated by Django 2.0.1 on 2018-02-06 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='response',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_and_time',
            field=models.DateTimeField(help_text='Enter the date and time of the event'),
        ),
    ]
