# Generated by Django 2.0.1 on 2018-02-07 01:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rsvp', '0003_auto_20180206_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='event',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='rsvp.Event'),
        ),
        migrations.RemoveField(
            model_name='guest',
            name='people',
        ),
        migrations.AddField(
            model_name='guest',
            name='people',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='event',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='rsvp.Event'),
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='people',
        ),
        migrations.AddField(
            model_name='vendor',
            name='people',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
