# Generated by Django 2.0.2 on 2018-02-10 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0007_question_userspecify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='plus',
            field=models.BooleanField(default=False, help_text='Can guests bring an additonal guest?'),
        ),
    ]
